version: '3.3'

services:
  omada-controller:
    container_name: omada-controller
    image: mbentley/omada-controller:5.13.30.8
    restart: unless-stopped
    network_mode: bridge
    ports:
      - '8088:8088'
      - '8043:8043'
      - '8843:8843'
      - '29810:29810/udp'
      - '29811:29811'
      - '29812:29812'
      - '29813:29813'
      - '29814:29814'
    environment:
      - PUID=508
      - PGID=508
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - PORT_APP_DISCOVERY=27001
      - PORT_ADOPT_V1=29812
      - PORT_UPGRADE_V1=29813
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      - SSL_CERT_NAME=tls.crt
      - SSL_KEY_NAME=tls.key
      - TZ=America/Mexico_City
      - TLS_1_11_ENABLED=true
    volumes:
      - /root/docker/omada/omada-data:/opt/tplink/EAPController/data
      - /root/docker/omada/omada-logs:/opt/tplink/EAPController/logs
      - /root/docker/omada/omada-work:/opt/tplink/EAPController/work
      - /root/docker/omada/omada-cert:/cert


volumes:
  omada-data:
  omada-logs:
  omada-work:
  omada-cert:
